config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'about', to: 'welcome#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title,
            presence: true,
            length: { within: 3..50 }

  validates :description,
            presence: true,
            length: { within: 10..300 }

  validates :user_id,
            presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name,
            presence: true,
            length: { within: 4..25 }
  validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }

  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { within: 3..25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    return if logged_in?
    flash[:danger] = 'You must be logged in to perform that action'
    redirect_to root_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update show destroy]
  before_action :require_user, except: %i[index show]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 10)
  end

  def new
    @article = Article.new
  end

  def edit
    set_article
  end

  def create
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article saved'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    set_article
    if @article.update(article_params)
      flash[:success] = 'Article updated'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
    set_article
  end

  def destroy
    set_article
    @article.destroy
    flash[:danger] = 'Article deleted'
    redirect_to articles_path
  end


  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    return if current_user == @article.user || current_user.admin?
    flash[:danger] = 'You can edit or delete only your own articles'
    redirect_to root_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[index show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category created'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.updated(category_params)
      flahs[:success] = 'Category updated'
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    return if logged_in? && current_user.admin?
    flash[:danger] = 'Only admin can perform this action'
    redirect_to categories_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'Login successful'
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Wrong login credentials'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Logout successful'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show destroy]
  before_action :require_user, only: %i[edit]
  before_action :require_same_user, only: %i[edit update destroy]
  before_action :require_admin, only: %i[destroy]


  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new

  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to A10-Blog #{@user.username}"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 10)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Account was updated'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:danger] = 'User account deleted'
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    return if current_user == @user || current_user.admin?
    flash[:danger] = 'You can edit only your own profile'
    redirect_to root_path
  end

  def require_admin
    return if logged_in? || current_user.admin?
    flash[:danger] = 'Only admin users can perform that action'
    redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<% obj.reverse_each do |article| %>
  <div class="card card-stack" style="width: 70rem;">

    <div class="card-body">
      <h4 class="card-title card-title-link"><%= link_to article.title, article_path(article) %></h4>
      <p class="card-text">
        <%= truncate(article.description, length: 100) %>
      </p>

      <p class="card-text">
        <small class="text-muted">
          Created by: <%= article.user.username if article.user %>
          <%= time_ago_in_words(article.created_at) %> ago,
          last updated: <%= time_ago_in_words(article.updated_at) %> ago.
        </small>
      </p>

      <% if article.categories.any? %>
        <p class="card-text text-muted">
          Categories:
          <%= render article.categories %>
        </p>
      <% end %>

      <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <div class="articles-actions">
          <%= link_to 'Delete', article_path(article), method: :delete,
                      data:                                    {confirm: 'Are you sure you want to delete the article?'},
                      class:                                   'btn btn-sm btn-danger card-link' %>

          <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-sm btn-primary' %>

          <%= link_to 'Show', article_path(article), class: 'btn btn-sm btn-success' %></div>
        </div>
      <% end %>
      </div>
  </div>
<% end %>

app/views/articles/_article.html.slim
- obj.reverse_each do |article|
  .card.card-stack style="width: 70rem;"
    .card-body
      
      h4.card-title.card-title-link 
        = link_to article.title, article_path(article)
      p.card-text
        = truncate(article.description, length: 100)
      
      p.card-text
        small.text-muted
          ' Created by:
          = article.user.username if article.user
          '
          = time_ago_in_words(article.created_at)
          '  ago, last updated:
          = time_ago_in_words(article.updated_at)
          |  ago.

      - if article.categories.any?
        p.card-text.text-muted
          | Categories:
          = render article.categories

      - if logged_in? && (current_user == article.user || current_user.admin?)
        .articles-actions
          = link_to 'Delete', article_path(article), method: :delete,
                      data: {confirm: 'Are you sure you want to delete the article?'},
                      class: 'btn btn-sm btn-danger card-link'

          = link_to 'Edit', edit_article_path(article), class: 'btn btn-sm btn-primary'

          = link_to 'Show', article_path(article), class: 'btn btn-sm btn-success'

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_for @article do |f| %>
  <div class="form-group row">
    <div class="col-sm-2 text-right font-weight-bold">
      <%= f.label :title, class: 'col-form-label ' %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :title, class: 'form-control', placeholder: 'Article Title' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2 text-right font-weight-bold">
      <%= f.label :description, class: 'col-form-label' %>
    </div>
    <div class="col-sm-8">
      <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: 'Article' %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 text-right font-weight-bold">
      Categories
    </div>
    <div class="col-sm-8">
      <div class="form-check form-check-inline">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <%= cb.label(class: 'form-check-label') { cb.check_box(class: 'form-check-input') + cb.text } %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <div class="offset-sm-2 col-sm-6">

      <%= link_to 'Back to list', articles_path, class: 'btn btn-primary' %>
      <%= f.submit class: 'btn btn-success' %>
    </div>
  </div>

<% end %>

app/views/articles/_form.html.slim
= render 'shared/errors', obj: @article

= form_for @article do |f|
  .form-group.row
    .col-sm-2.text-right.font-weight-bold
      = f.label :title, class: 'col-form-label'
    .col-sm-8
      = f.text_field :title, class: 'form-control', placeholder: 'Article Title'

  .form-group.row
    .col-sm-2.text-right.font-weight-bold
      = f.label :description, class: 'col-form-label'
    .col-sm-8
      = f.text_area :description, rows: 10, class: 'form-control', placeholder: 'Article'

  .row
    .col-sm-2.text-right.font-weight-bold
      | Categories
    .col-sm-8
      .form-check.form-check-inline
        - f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|
          = cb.label(class: 'form-check-label') { cb.check_box(class: 'form-check-input') + cb.text }

  .form-group.row
    .offset-sm-2.col-sm-6
      = link_to 'Back to list', articles_path, class: 'btn btn-primary'
      = f.submit class: 'btn btn-success'

app/views/articles/edit.html.erb
<h1 align="center">Edit article</h1>

<%= render 'form' %>

app/views/articles/edit.html.slim
h1 align="center" Edit article

= render 'form'

app/views/articles/index.html.erb
<h2 align="center">Listing all articles</h2>
<div class="pagination justify-content-center">
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div class="pagination justify-content-center pagination-bottom">
  <%= will_paginate %>
</div>

app/views/articles/index.html.slim
h2 align="center" Listing all articles
.pagination.justify-content-center
  = will_paginate

= render 'article', obj: @articles

.pagination.justify-content-center.pagination-bottom
  = will_paginate

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>

<%= render 'form' %>

app/views/articles/new.html.slim
h1 align="center" Create an article

= render 'form'

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %> </h2>

<div class="card" style="width: 70rem;">
  <div class="card-body">
    <h5 class="card-title">Created by: <%= link_to @article.user.username, user_path(@article.user) %></h5>
    <p class="card-text">
      <%= simple_format(@article.description) %>
    </p>
    <p class="card-text">
      <small class="text-muted">
        Created by: <%= @article.user.username if @article.user %>
        <%= time_ago_in_words(@article.created_at) %> ago,
        last updated: <%= time_ago_in_words(@article.updated_at) %> ago.
      </small>
    </p>

    <% if @article.categories.any? %>
      <p class="card-text text-muted">
        Categories:
        <%= render @article.categories %>
      </p>
    <% end %>

    <div class="articles-actions">
      <% if logged_in? && current_user == @article.user || current_user.admin? %>
        <%= link_to 'Delete', articles_path, method: :delete,
                    data:                            {confirm: 'Are you sure you want to delete the article?'},
                    class:                           'btn btn-sm btn-danger card-link' %>
        <%= link_to 'Edit', edit_article_path, class: 'btn btn-sm btn-primary' %>
      <% end %>
      <%= link_to 'Back to list', articles_path, class: 'btn btn-sm btn-success' %>
    </div>
  </div>
</div>

app/views/articles/show.html.slim
h2 align="center"
  = @article.title

.card style="width: 70rem;"
  .card-body
    h5.card-title
      ' Created by:
      = link_to @article.user.username, user_path(@article.user)
    p.card-text
      = simple_format(@article.description)

    p.card-text
      small.text-muted
        ' Created by:
        = @article.user.username if @article.user
        = time_ago_in_words(@article.created_at)
        '  ago, last updated:
        = time_ago_in_words(@article.updated_at)
        |  ago.

    - if @article.categories.any?
      p.card-text.text-muted
        | Categories:
        = render @article.categories

    .articles-actions
      - if logged_in? && current_user == @article.user || current_user.admin?
        = link_to 'Delete', articles_path, method: :delete,
                    data: {confirm: 'Are you sure you want to delete the article?'},
                    class: 'btn btn-sm btn-danger card-link'
        = link_to 'Edit', edit_article_path, class: 'btn btn-sm btn-primary'
      = link_to 'Back to list', articles_path, class: 'btn btn-sm btn-success'

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: 'badge badge-info' %> &nbsp;

app/views/categories/_category.html.slim
= link_to category.name, category_path(category), class: 'badge badge-info'
| &nbsp

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for @category do |f| %>
  <div class="form-group row">
    <div class="col-sm-2 text-right font-weight-bold">
      <%= f.label :name, class:'col-form-label ' %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class:'form-control', placeholder:'Category name' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="offset-sm-2 col-sm-6">

      <%= link_to 'Back to list', categories_path, class:'btn btn-primary' %>
      <%= f.submit class:'btn btn-success' %>
    </div>
  </div>

<% end %>

app/views/categories/_form.html.slim
= render 'shared/errors', obj: @category

= form_for @category do |f|
  .form-group.row
    .col-sm-2.text-right.font-weight-bold
      = f.label :name, class:'col-form-label '
    .col-sm-8
      = f.text_field :name, class:'form-control', placeholder:'Category name'

  .form-group.row
    .offset-sm-2.col-sm-6
      = link_to 'Back to list', categories_path, class:'btn btn-primary'
      = f.submit class:'btn btn-success'

app/views/categories/edit.html.erb
<h1 align="center">Edit <%= @category.name %> category</h1>

<%= render 'form' %>

app/views/categories/edit.html.slim
h1 align="center"
  ' Edit
  = @category.name
  |  category

= render 'form'

app/views/categories/index.html.erb
<h2 align="center">Listing all categories</h2>

<div class="pagination justify-content-center">
  <%= will_paginate %>
</div>

<% @categories.each do |category| %>
    <div class="card card-stack" style="width: 70rem;">

      <div class="card-body">
        <h4 class="card-title card-title-link">Category: <%= link_to category.name, category_path(category) %></h4>

        <p class="card-text">
          <%= pluralize(category.articles.count, 'article') %>
        </p>

        </div>
    </div>
<% end %>

<div class="pagination justify-content-center">
  <%= will_paginate %>
</div>

app/views/categories/index.html.slim
h2 align="center" Listing all categories

.pagination.justify-content-center
  = will_paginate

- @categories.each do |category|
    .card.card-stack style="width: 70rem;"
      .card-body
        h4.card-title.card-title-link
          ' Category:
          = link_to category.name, category_path(category)

        p.card-text
          = pluralize(category.articles.count, 'article')

.pagination.justify-content-center
  = will_paginate

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>

app/views/categories/new.html.slim
h1 align="center" Create new category

= render 'form'

app/views/categories/show.html.erb
<div class="row">
  <h2 class="offset-sm-4 col-sm-4"><%= 'Category: ' + @category.name %></h2>
  <% if logged_in? && current_user.admin? %>
    <div class="offset-sm-2 col-sm-1">
      <%= link_to 'Edit category', edit_category_path(@category), class: 'btn btn-sm btn-primary' %>
    </div>
    <% end %>
</div>

<div class="pagination justify-content-center">
  <%= will_paginate @category_articles %>
</div>

<%= render 'articles/article', obj: @category_articles %>

<div class="pagination justify-content-center pagination-bottom">
  <%= will_paginate @category_articles %>
</div>

app/views/categories/show.html.slim
.row
  h2.offset-sm-4.col-sm-4
    ' Category:
    = @category.name
  - if logged_in? && current_user.admin?
    .offset-sm-2.col-sm-1
      = link_to 'Edit category', edit_category_path(@category), class: 'btn btn-sm btn-primary'

.pagination.justify-content-center
  = will_paginate @category_articles

= render 'articles/article', obj: @category_articles

.pagination.justify-content-center.pagination-bottom
  = will_paginate @category_articles

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">Created by Cezary Kłos for The Complete Ruby on Rails Developer Udemy course.</span>
  </div>
</footer>

app/views/layouts/_footer.html.slim
footer.footer
  .container
    span.text-muted Created by Cezary Kłos.

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.slim
.row
  .col-sm
    - flash.each do |name, msg|
      - alert_class = "alert-" + name
      div class= "alert" class= alert_class
        a href='#' class='close' data-dismiss='alert' &#215
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top ">
  <a class="navbar-brand" href="#">A-10 Thunderbolt II</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample04">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Articles', articles_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Users', users_path, class: 'nav-link' %>
      </li>

      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to 'New article', new_article_path, class: 'nav-link' %>
        </li>
      <% end %>

      <div class="nav-item dropdown">
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">

          <% if logged_in? && current_user.admin? %>
              <%= link_to 'New category', new_category_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
        <% end %>
          <%= link_to 'All categories', categories_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <% Category.all.each do |category| %>
              <%= link_to category.name, category_path(category), class: 'dropdown-item' %>
          <% end %>

        </div>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false"> Categories </a>
      </div>
    </ul>


    </ul>

    <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to 'About', about_path, class: 'nav-link'  %>
    </li>
    <% if logged_in? %>

        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
             aria-haspopup="true" aria-expanded="false"> <%= current_user.username %> </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'View profile', user_path(current_user), class: 'dropdown-item' %>
            <%= link_to 'Edit profile', edit_user_path(current_user), class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
            <%= link_to 'Log out', logout_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </div>
        </ul>
    <% else %>
      <span class="nav-item"><%= link_to 'Log in', login_path, class: 'nav-link' %></span>
      <span class="nav-item"><%= link_to 'Sign up', signup_path, class: 'nav-link' %></span>
    <% end %>

  </div>
</nav>

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-expand-md.navbar-dark.bg-dark.fixed-top
  a.navbar-brand href='#' A-10 Thunderbolt II
  button.navbar-toggler type='button' data-toggle='collapse' data-target='#navbarsExample04' aria-controls='navbarsExample04' aria-expanded='false' aria-label='Toggle navigation'
    span.navbar-toggler-icon

  .collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item
        = link_to 'Home', root_path, class: 'nav-link'

      li.nav-item
        = link_to 'Articles', articles_path, class: 'nav-link'

      li.nav-item
        = link_to 'Users', users_path, class: 'nav-link'

      - if logged_in?
        li.nav-item
          = link_to 'New article', new_article_path, class: 'nav-link'

      li.nav-item.dropdown
        a.nav-link.dropdown-toggle href='#' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false' Categories
        .dropdown-menu.dropdown-menu-right aria-labelledby='navbarDropdownMenuLink'
          - if logged_in? && current_user.admin?
            = link_to 'New category', new_category_path, class: 'dropdown-item'
            .dropdown-divider

          = link_to 'All categories', categories_path, class: 'dropdown-item'
          .dropdown-divider
          - Category.all.each do |category|
            = link_to category.name, category_path(category), class: 'dropdown-item'

    ul.navbar-nav
      li.nav-item
        = link_to 'About', about_path, class: 'nav-link'

      - if logged_in?
        li.nav-item.dropdown
          a.nav-link.dropdown-toggle href='#' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false' = current_user.username
          .dropdown-menu.dropdown-menu-right aria-labelledby='navbarDropdownMenuLink'
            = link_to 'View profile', user_path(current_user), class: 'dropdown-item'
            = link_to 'Edit profile', edit_user_path(current_user), class: 'dropdown-item'
            .dropdown-divider
            = link_to 'Log out', logout_path, method: :delete, class: 'dropdown-item'
      - else
        span.nav-item
          = link_to 'Log in', login_path, class: 'nav-link'
        span.nav-item
          = link_to 'Sign up', signup_path, class: 'nav-link'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <title>A10-Blog</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
  <body>

  <%= render 'layouts/navigation' %>

  <main role="main" class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </main>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    / Required meta tags
    title A10-Blog
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    / Bootstrap CSS
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'layouts/navigation'

    main role="main" class="container"
      = render 'layouts/messages'
      == yield

    = render 'layouts/footer'
    = debug(params) if Rails.env.development?

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="col-sm-8 offset-sm-2">
      <div class="alert alert-warning" role="alert">
        <h2 class="alert-heading"><%= pluralize(obj.errors.count, 'error') %> prevented from saving article</h2>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
              <li> <%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

app/views/shared/_errors.html.slim
- if obj.errors.any?
  .col-sm-8.offset-sm-2
    .alert.alert-warning role= alert
      h2.alert-heading
        = pluralize(obj.errors.count, 'error')
          | prevented from saving article
      ul
        - obj.errors.full_messages.each do |msg|
          li = msg

app/views/users/_form.html.slim
= render 'shared/errors', obj: @user

= form_for @user do |f|
  .form-group.row
    .col-sm-2.text-right.font-weight-bold
      = f.label :username, class:'col-form-label '
    .col-sm-8 
      = f.text_field :username, class:'form-control', placeholder:'Username'  

  .form-group.row
    .col-sm-2.text-right.font-weight-bold
      = f.label :email, class:'col-form-label'
    .col-sm-8 
      = f.email_field :email, class:'form-control', placeholder:'email'   

  .form-group.row
    .col-sm-2.text-right.font-weight-bold
      = f.label :password, class:'col-form-label'
    .col-sm-8 
      = f.password_field :password, class:'form-control', placeholder:'Password'   

  .form-group.row
    .offset-sm-2.col-sm-6
      = link_to 'Back to list', articles_path, class:'btn btn-primary'
      = f.submit(@user.new_record? ? 'Sign up' : 'Update account', class:'btn btn-success')

app/views/users/edit.html.erb
<h1 align="center">Edit account</h1>

<%= render 'form' %>

app/views/users/edit.html.slim
h1 align="center" Edit account

= render 'form'